// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using apoemaMatch.Data;

namespace apoemaMatch.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.6")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("apoemaMatch.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nome")
                        .HasColumnType("text");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("apoemaMatch.Models.Chamada", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("ArquivoAnexo")
                        .HasColumnType("text");

                    b.Property<DateTime>("DataValidade")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("DescricaoChamada")
                        .HasColumnType("text");

                    b.Property<int>("EncomendaId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EncomendaId")
                        .IsUnique();

                    b.ToTable("Chamada");
                });

            modelBuilder.Entity("apoemaMatch.Models.Criterio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int?>("ChamadaId")
                        .HasColumnType("integer");

                    b.Property<string>("Descricao")
                        .HasColumnType("text");

                    b.Property<int>("Ordem")
                        .HasColumnType("integer");

                    b.Property<int>("TipoCriterio")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ChamadaId");

                    b.ToTable("Criterio");
                });

            modelBuilder.Entity("apoemaMatch.Models.Demandante", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("AreaSolucaoBuscada")
                        .HasColumnType("integer");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<string>("CargoDemandante")
                        .HasColumnType("text");

                    b.Property<string>("Cnpj")
                        .HasColumnType("text");

                    b.Property<string>("Descricao")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("IdUsuario")
                        .HasColumnType("text");

                    b.Property<string>("ImagemURL")
                        .HasColumnType("text");

                    b.Property<int>("LeiDeInformatica")
                        .HasColumnType("integer");

                    b.Property<int>("LinhaDeAtuacaoTI")
                        .HasColumnType("integer");

                    b.Property<string>("NomeDemandante")
                        .HasColumnType("text");

                    b.Property<string>("NomeEmpresa")
                        .HasColumnType("text");

                    b.Property<int>("ObjetivoParceria")
                        .HasColumnType("integer");

                    b.Property<int>("PorteDaEmpresa")
                        .HasColumnType("integer");

                    b.Property<int>("RamoDeAtuacao")
                        .HasColumnType("integer");

                    b.Property<int>("RegimeDeTributacao")
                        .HasColumnType("integer");

                    b.Property<int>("SegmentoDeMercado")
                        .HasColumnType("integer");

                    b.Property<string>("Telefone")
                        .HasColumnType("text");

                    b.Property<int>("TempoDeMercado")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Demandantes");
                });

            modelBuilder.Entity("apoemaMatch.Models.Encomenda", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("DemandanteId")
                        .HasColumnType("integer");

                    b.Property<string>("Descricao")
                        .HasColumnType("text");

                    b.Property<bool>("EncomendaAberta")
                        .HasColumnType("boolean");

                    b.Property<int>("IdDemandante")
                        .HasColumnType("integer");

                    b.Property<int?>("IdSolucionador")
                        .HasColumnType("integer");

                    b.Property<string>("JustificativaRecusa")
                        .HasColumnType("text");

                    b.Property<bool>("PossuiChamada")
                        .HasColumnType("boolean");

                    b.Property<int>("StatusEncomenda")
                        .HasColumnType("integer");

                    b.Property<int>("TipoEncomenda")
                        .HasColumnType("integer");

                    b.Property<string>("Titulo")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DemandanteId");

                    b.ToTable("Encomendas");
                });

            modelBuilder.Entity("apoemaMatch.Models.OpcaoCriterio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int?>("CriterioId")
                        .HasColumnType("integer");

                    b.Property<int?>("RespostaCriterioId")
                        .HasColumnType("integer");

                    b.Property<string>("Texto")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CriterioId");

                    b.HasIndex("RespostaCriterioId");

                    b.ToTable("OpcaoCriterio");
                });

            modelBuilder.Entity("apoemaMatch.Models.Proposta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("ChamadaId")
                        .HasColumnType("integer");

                    b.Property<int?>("SolucionadorId")
                        .HasColumnType("integer");

                    b.Property<int>("StatusProposta")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ChamadaId");

                    b.HasIndex("SolucionadorId");

                    b.ToTable("Proposta");
                });

            modelBuilder.Entity("apoemaMatch.Models.RespostaCriterio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("CriterioId")
                        .HasColumnType("integer");

                    b.Property<int>("Nota")
                        .HasColumnType("integer");

                    b.Property<int?>("PropostaId")
                        .HasColumnType("integer");

                    b.Property<string>("RespostaTextual")
                        .HasColumnType("text");

                    b.Property<string>("RespostaUpload")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CriterioId");

                    b.HasIndex("PropostaId");

                    b.ToTable("RespostaCriterio");
                });

            modelBuilder.Entity("apoemaMatch.Models.Solucionador", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("AreaDePesquisa")
                        .HasColumnType("integer");

                    b.Property<string>("Cpf")
                        .HasColumnType("text");

                    b.Property<string>("CurriculoLattes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Disponivel")
                        .HasColumnType("boolean");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Formacao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("IdUsuario")
                        .HasColumnType("text");

                    b.Property<string>("ImagemURL")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MiniBio")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Solucionadores");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("apoemaMatch.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("apoemaMatch.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("apoemaMatch.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("apoemaMatch.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("apoemaMatch.Models.Chamada", b =>
                {
                    b.HasOne("apoemaMatch.Models.Encomenda", "Encomenda")
                        .WithOne("Chamada")
                        .HasForeignKey("apoemaMatch.Models.Chamada", "EncomendaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Encomenda");
                });

            modelBuilder.Entity("apoemaMatch.Models.Criterio", b =>
                {
                    b.HasOne("apoemaMatch.Models.Chamada", null)
                        .WithMany("Criterios")
                        .HasForeignKey("ChamadaId");
                });

            modelBuilder.Entity("apoemaMatch.Models.Encomenda", b =>
                {
                    b.HasOne("apoemaMatch.Models.Demandante", "Demandante")
                        .WithMany()
                        .HasForeignKey("DemandanteId");

                    b.Navigation("Demandante");
                });

            modelBuilder.Entity("apoemaMatch.Models.OpcaoCriterio", b =>
                {
                    b.HasOne("apoemaMatch.Models.Criterio", null)
                        .WithMany("OpcoesCriterios")
                        .HasForeignKey("CriterioId");

                    b.HasOne("apoemaMatch.Models.RespostaCriterio", null)
                        .WithMany("OpcoesSelecionadas")
                        .HasForeignKey("RespostaCriterioId");
                });

            modelBuilder.Entity("apoemaMatch.Models.Proposta", b =>
                {
                    b.HasOne("apoemaMatch.Models.Chamada", "Chamada")
                        .WithMany("Propostas")
                        .HasForeignKey("ChamadaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("apoemaMatch.Models.Solucionador", "Solucionador")
                        .WithMany()
                        .HasForeignKey("SolucionadorId");

                    b.Navigation("Chamada");

                    b.Navigation("Solucionador");
                });

            modelBuilder.Entity("apoemaMatch.Models.RespostaCriterio", b =>
                {
                    b.HasOne("apoemaMatch.Models.Criterio", "Criterio")
                        .WithMany()
                        .HasForeignKey("CriterioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("apoemaMatch.Models.Proposta", null)
                        .WithMany("RespostasCriterios")
                        .HasForeignKey("PropostaId");

                    b.Navigation("Criterio");
                });

            modelBuilder.Entity("apoemaMatch.Models.Chamada", b =>
                {
                    b.Navigation("Criterios");

                    b.Navigation("Propostas");
                });

            modelBuilder.Entity("apoemaMatch.Models.Criterio", b =>
                {
                    b.Navigation("OpcoesCriterios");
                });

            modelBuilder.Entity("apoemaMatch.Models.Encomenda", b =>
                {
                    b.Navigation("Chamada");
                });

            modelBuilder.Entity("apoemaMatch.Models.Proposta", b =>
                {
                    b.Navigation("RespostasCriterios");
                });

            modelBuilder.Entity("apoemaMatch.Models.RespostaCriterio", b =>
                {
                    b.Navigation("OpcoesSelecionadas");
                });
#pragma warning restore 612, 618
        }
    }
}
